
@url = http://localhost:5155
@docker_url = http://localhost:8080

### View OpenApi doc
GET {{url}}/openapi/v1.json
Accept: application/json
###

### Endpionts when running directly

GET {{url}}/weatherforecast
###

GET {{url}}/weatherforecast/city/Palmerston North
###

GET {{url}}/GitHubUser/validate/chrisyoxall
###

GET {{url}}/health
###


### Endpoints when running in Docker ###

GET {{docker_url}}/weatherforecast
###

GET {{docker_url}}/health

